### ISSUE TITLE
svg inside of template causes error with v1.1.0

### ISSUE THREAD

**Issue by dbatiste** [43081j/eslint-plugin-lit#54]
With v1.1.0 (but works is fine with v1.0.0), the following:
```
import { html, LitElement } from 'lit-element/lit-element.js';

class SvgTest extends LitElement {
   render() {
      return html`
         <svg viewBox="0 0 48 48">
         </svg>
      `;
   }
}
```
appears to cause this error:
```
TypeError: Cannot read property 'endOffset' of undefined
Occurred while linting /Users/dbatiste/source/brightspace-ui/core/components/meter/svg-test.js:5
    at TemplateAnalyzer.getRawAttributeValue (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/template-analyzer.js:98:21)
    at Object.enterElement (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/rules/attribute-value-entities.js:43:59)
    at visit (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/template-analyzer.js:159:29)
    at children.forEach (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/template-analyzer.js:166:25)
    at Array.forEach (<anonymous>)
    at visit (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/template-analyzer.js:165:30)
    at TemplateAnalyzer.traverse (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/template-analyzer.js:174:9)
    at TaggedTemplateExpression (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint-plugin-lit/lib/rules/attribute-value-entities.js:38:30)
    at listeners.(anonymous function).forEach.listener (/Users/dbatiste/source/brightspace-ui/core/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
```
However, the following does not cause the error.  The difference being the attribute for the `svg`:
```
import { html, LitElement } from 'lit-element/lit-element.js';

class SvgTest extends LitElement {
   render() {
      return html`
         <svg>
         </svg>
      `;
   }
}
```

**Comment by 43081j** [comment]
this is due to some fun behaviour parse5 parser has.

specifically for svg elements, it maps the `viewBox` attribute name to be the correct casing whereas all other case-sensitive attributes on all other elements are lowercased.

good find!

**Comment by dbatiste** [comment]
Thanks James!
